 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/relationships", type: :request do
  
  # Relationship. As you add validations to Relationship, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Relationship.create! valid_attributes
      get relationships_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      relationship = Relationship.create! valid_attributes
      get relationship_url(relationship)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_relationship_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      relationship = Relationship.create! valid_attributes
      get edit_relationship_url(relationship)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Relationship" do
        expect {
          post relationships_url, params: { relationship: valid_attributes }
        }.to change(Relationship, :count).by(1)
      end

      it "redirects to the created relationship" do
        post relationships_url, params: { relationship: valid_attributes }
        expect(response).to redirect_to(relationship_url(Relationship.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Relationship" do
        expect {
          post relationships_url, params: { relationship: invalid_attributes }
        }.to change(Relationship, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post relationships_url, params: { relationship: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested relationship" do
        relationship = Relationship.create! valid_attributes
        patch relationship_url(relationship), params: { relationship: new_attributes }
        relationship.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the relationship" do
        relationship = Relationship.create! valid_attributes
        patch relationship_url(relationship), params: { relationship: new_attributes }
        relationship.reload
        expect(response).to redirect_to(relationship_url(relationship))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        relationship = Relationship.create! valid_attributes
        patch relationship_url(relationship), params: { relationship: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested relationship" do
      relationship = Relationship.create! valid_attributes
      expect {
        delete relationship_url(relationship)
      }.to change(Relationship, :count).by(-1)
    end

    it "redirects to the relationships list" do
      relationship = Relationship.create! valid_attributes
      delete relationship_url(relationship)
      expect(response).to redirect_to(relationships_url)
    end
  end
end
